### ISSUE TITLE
Bogwood Sapling not rendered correctly

### ISSUE THREAD

**Issue by Lolothepro** [TheSlayerMC/JITL#12]
Minecraft: 1.20.6
NeoForge: 20.6.63-beta
JITL: JITL - 1.20.6 - 2.1.4

![2024-05-15_20 58 58](https://github.com/TheSlayerMC/JITL/assets/68275908/e1972724-c5bf-41d8-94bf-d4e2c7239048)

Is it possible to fix this bug?

**Comment by IMS212** [comment]
It seems like a similar issue may be happening with Crystal Fruit; the outcome is not visible in Vanilla but it isn't being set to the right layer.

**Comment by AllShamNoWow101** [comment]
Has been fixed for next release
