### ISSUE TITLE
Mobs in the nether 

### ISSUE THREAD

**Issue by ZyrusHub** [TheSlayerMC/JITL#19]
Your mobs are over spawning in the warped forest region of the nether stopping ender men spawning i have been to many different warped forest biomes and have not found one enderman.

**Comment by samjviana** [comment]
+1 on this, it was a journey to find ghasts ... i think the main problem relies on the hell cow, but i'm not sure.

**Comment by AllShamNoWow101** [comment]
I can lower hell cow spawn rate in next version and can see if that fixes it

**Comment by samjviana** [comment]
> I can lower hell cow spawn rate in next version and can see if that fixes it

I did some debugging and noticed that the Hell Cow is registered as a `MONSTER`, making it a hostile mob and sharing the mob cap with ghasts, piglins, etc. I'm not sure if registering it as hostile is intended, but I think changing it to `CREATURE` can improve the results here.

_I can test this it later ^~^_
