### ISSUE TITLE
jitl 1.20.1 world load halt due to outdated structure 

### ISSUE THREAD

**Issue by SDUBZ** [TheSlayerMC/JITL#2]
minecraft:1.20.1
forge:47.1.33
jitl: Journey-Into-The-Light-1.20.1-2.0.0.13
logs:
[debug.log](https://github.com/TheSlayerMC/JITL/files/12076606/debug.log)
[latest.log](https://github.com/TheSlayerMC/JITL/files/12076607/latest.log)

**Comment by AllShamNoWow101** [comment]
Doesnt seem to be caused by jitl
