### ISSUE TITLE
add config to disable first join book

### ISSUE THREAD

**Issue by VaporeonScripts** [TheSlayerMC/JITL#21]
![image](https://github.com/user-attachments/assets/faafea72-4498-4214-99d6-a536b2f53bad)
this one

**Comment by AllShamNoWow101** [comment]
Hi if you dont want the book you can not use patchouli?

**Comment by VaporeonScripts** [comment]
I don't have patchouli

**Comment by AllShamNoWow101** [comment]
Then how do you get the guide book if you dont have patchouli installed?

**Comment by VaporeonScripts** [comment]
Some mod has it embedded,anyways now that I think abt it I wanted to remove it cuz it was broken before 2.2but now it's fixed so I can keep it to see what to do
