### ISSUE TITLE
Deepslate Verdite Ore cannot be smelt

### ISSUE THREAD

**Issue by samjviana** [TheSlayerMC/JITL#22]
There isn’t any recipe for the Deepslate Verdite Ore. I managed to work around it by adding a `verdite_ore` tag and using it in the `verdite_ingot` recipe. While I managed to fix it for myself, I just wanted to point this out ^~^

<br><br>
_This is the changes I made, hope this can be helpful to someone:_
<details>
  <summary><code>Tag</code></summary>
  
```json
{
  "replace": false,
  "values": [
    "jitl:verdite_ore",
    "jitl:deepslate_verdite_ore"
  ]
}
```
</details>

<details>
  <summary><code>Recipes</code></summary>
  
```json
{
  "type": "minecraft:smelting",
  "category": "misc",
  "cookingtime": 200,
  "experience": 1.0,
  "ingredient": {
    "tag": "jitl:verdite_ore"
  },
  "result": {
    "count": 1,
    "id": "jitl:verdite_ingot"
  }
}
```

```json
{
  "type": "minecraft:blasting",
  "category": "misc",
  "cookingtime": 100,
  "experience": 1.0,
  "ingredient": {
    "tag": "jitl:verdite_ore"
  },
  "result": {
    "count": 1,
    "id": "jitl:verdite_ingot"
  }
}
```
</details>

**Comment by AllShamNoWow101** [comment]
I will fix this next version
