### ISSUE TITLE
JITL1.20.1-2.0.0.15 Cannot invoke "net.minecraft.core.NonNullList.get(int)" because "this.f_21350_" is null

### ISSUE THREAD

**Issue by NancalaStarry** [TheSlayerMC/JITL#4]
[lastest.log](https://github.com/TheSlayerMC/JITL/files/14151448/lastest.log)

**Comment by WolfBV** [comment]
@NancalaStarry Try again with Journey-Into-The-Light-1.20.1 - 2.1
