### ISSUE TITLE
1.20.1, crash when creating a world, Journey Into The Light and L2 Library

### ISSUE THREAD

**Issue by WolfBV** [TheSlayerMC/JITL#6]
Forge 47.1.3
Journey-Into-The-Light-1.20.1 - 2.1
curios-forge-5.7.2+1.20.1
geckolib-forge-1.20.1-4.4.4
l2library-2.4.24

Download Journey Into The Light, Curios, Geckolib, L2 Library. Launch game, create new world, crash.

[latest.log](https://github.com/TheSlayerMC/JITL/files/14895478/latest.log)

Pastebin version of latest.log: https://pastebin.com/DFXYPgF0

**Comment by AllShamNoWow101** [comment]
Hi this problem seems to be with Curios mod

**Comment by lcy0x1** [comment]
@TheSlayerMC It's JIT's problem

https://github.com/TheSlayerMC/JITL/blob/b9f0af8c88d72ea00a98e9334ba40a84f76f984b/src/main/java/net/jitl/common/event/GearAbilityHandler.java#L34

You are not allowed to set event priority in event handlers.

**Comment by AllShamNoWow101** [comment]
Smh thats code from an old dev, will remove

**Comment by WolfBV** [comment]
No longer occurs with Journey Into The Light 2.1.3.
